# Gradle 项目全局配置
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# HTTP 代理配置（加速依赖下载）
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=10808
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=10808

# AndroidX 支持
android.useAndroidX=true

# Kotlin 官方代码风格
kotlin.code.style=official

# 非传递性 R 类，减小 APK 体积
android.nonTransitiveRClass=true
